/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityLevel = { 'active' : null } |
  { 'veryActive' : null } |
  { 'light' : null } |
  { 'sedentary' : null } |
  { 'moderate' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Challenge {
  'id' : bigint,
  'status' : ChallengeStatus,
  'title' : string,
  'rewardPoints' : bigint,
  'description' : string,
  'progress' : bigint,
  'target' : bigint,
  'rewardBadge' : string,
}
export type ChallengeStatus = { 'active' : null } |
  { 'completed' : null };
export interface ChatRequest {
  'coach' : CoachType,
  'message' : string,
  'profile' : UserProfile,
}
export interface ChatResponse { 'reply' : string }
export type CoachType = { 'gym' : null } |
  { 'basketball' : null } |
  { 'swimming' : null } |
  { 'football' : null } |
  { 'diet' : null } |
  { 'cricket' : null };
export interface DailyFoodLog {
  'totalCarbs' : number,
  'totalFat' : number,
  'entries' : Array<FoodLogEntry>,
  'totalCalories' : number,
  'totalProtein' : number,
}
export interface DietTarget {
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'protein' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Exercise { 'name' : string, 'sets' : Array<WorkoutSet> }
export type FitnessGoal = { 'gain' : null } |
  { 'lose' : null } |
  { 'maintain' : null };
export interface FoodLogEntry {
  'id' : bigint,
  'loggedAtNs' : bigint,
  'servingSize' : number,
  'product' : FoodProduct,
}
export interface FoodProduct {
  'fat' : number,
  'carbs' : number,
  'code' : string,
  'calories' : number,
  'name' : string,
  'protein' : number,
}
export interface FriendRequest {
  'to' : Principal,
  'status' : FriendRequestStatus,
  'from' : Principal,
}
export type FriendRequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface FriendView {
  'principal' : Principal,
  'name' : string,
  'rank' : RankInfo,
  'challengeProgress' : Array<Challenge>,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Profile {
  'age' : bigint,
  'activityLevel' : ActivityLevel,
  'targetSport' : string,
  'heightCm' : number,
  'goal' : FitnessGoal,
  'name' : string,
  'weightKg' : number,
  'gender' : Gender,
}
export interface RankInfo {
  'xp' : bigint,
  'tier' : RankTier,
  'level' : bigint,
  'xpToNextLevel' : bigint,
}
export type RankTier = { 'bronze' : null } |
  { 'gold' : null } |
  { 'diamond' : null } |
  { 'platinum' : null } |
  { 'silver' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : FoodProduct } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface Reward {
  'id' : bigint,
  'earnedAtNs' : bigint,
  'badge' : string,
  'points' : bigint,
}
export interface SearchResult { 'principal' : Principal, 'profile' : Profile }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface UserProfile {
  'age' : bigint,
  'goal' : string,
  'weightKg' : number,
  'gender' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Workout {
  'id' : bigint,
  'completedAtNs' : bigint,
  'title' : string,
  'exercises' : Array<Exercise>,
}
export interface WorkoutSet { 'reps' : bigint, 'weightKg' : number }
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_2>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chat' : ActorMethod<[ChatRequest], ChatResponse>,
  'deleteFoodEntry' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[], Array<Challenge>>,
  'getDailyFoodLog' : ActorMethod<[], DailyFoodLog>,
  'getDietTarget' : ActorMethod<[], DietTarget>,
  'getFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getFriends' : ActorMethod<[], Array<FriendView>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getRankInfo' : ActorMethod<[], RankInfo>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logFood' : ActorMethod<[FoodProduct, number], undefined>,
  'logWorkout' : ActorMethod<[string, Array<Exercise>], undefined>,
  'respondToFriendRequest' : ActorMethod<[Principal, boolean], Result>,
  'schema' : ActorMethod<[], string>,
  'searchFoodByBarcode' : ActorMethod<[string], Result_1>,
  'searchUsers' : ActorMethod<[string], Array<SearchResult>>,
  'sendFriendRequest' : ActorMethod<[Principal], Result>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateFoodEntry' : ActorMethod<[bigint, number], undefined>,
  'updateProfile' : ActorMethod<[Profile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];