/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CoachType = IDL.Variant({
  'gym' : IDL.Null,
  'basketball' : IDL.Null,
  'swimming' : IDL.Null,
  'football' : IDL.Null,
  'diet' : IDL.Null,
  'cricket' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'goal' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : IDL.Text,
});
export const ChatRequest = IDL.Record({
  'coach' : CoachType,
  'message' : IDL.Text,
  'profile' : UserProfile,
});
export const ChatResponse = IDL.Record({ 'reply' : IDL.Text });
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ChallengeProof = IDL.Record({
  'id' : IDL.Nat,
  'proofRef' : IDL.Text,
  'challengeId' : IDL.Nat,
  'submittedAtNs' : IDL.Int,
});
export const ChallengeStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'status' : ChallengeStatus,
  'title' : IDL.Text,
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'target' : IDL.Nat,
  'rewardBadge' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'sentAtNs' : IDL.Int,
  'from' : IDL.Principal,
  'text' : IDL.Text,
});
export const Conversation = IDL.Record({
  'messages' : IDL.Vec(ChatMessage),
  'friend' : IDL.Principal,
});
export const FoodProduct = IDL.Record({
  'fat' : IDL.Float64,
  'carbs' : IDL.Float64,
  'code' : IDL.Text,
  'calories' : IDL.Float64,
  'name' : IDL.Text,
  'protein' : IDL.Float64,
});
export const FoodLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'loggedAtNs' : IDL.Int,
  'servingSize' : IDL.Float64,
  'product' : FoodProduct,
});
export const DailyFoodLog = IDL.Record({
  'totalCarbs' : IDL.Float64,
  'totalFat' : IDL.Float64,
  'entries' : IDL.Vec(FoodLogEntry),
  'totalCalories' : IDL.Float64,
  'totalProtein' : IDL.Float64,
});
export const DietTarget = IDL.Record({
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const FriendRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const FriendRequest = IDL.Record({
  'to' : IDL.Principal,
  'status' : FriendRequestStatus,
  'from' : IDL.Principal,
});
export const RankTier = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'diamond' : IDL.Null,
  'platinum' : IDL.Null,
  'silver' : IDL.Null,
});
export const RankInfo = IDL.Record({
  'xp' : IDL.Nat,
  'tier' : RankTier,
  'level' : IDL.Nat,
  'xpToNextLevel' : IDL.Nat,
});
export const FriendView = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'rank' : RankInfo,
  'challengeProgress' : IDL.Vec(Challenge),
});
export const ActivityLevel = IDL.Variant({
  'active' : IDL.Null,
  'veryActive' : IDL.Null,
  'light' : IDL.Null,
  'sedentary' : IDL.Null,
  'moderate' : IDL.Null,
});
export const FitnessGoal = IDL.Variant({
  'gain' : IDL.Null,
  'lose' : IDL.Null,
  'maintain' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'activityLevel' : ActivityLevel,
  'targetSport' : IDL.Text,
  'heightCm' : IDL.Float64,
  'goal' : FitnessGoal,
  'name' : IDL.Text,
  'weightKg' : IDL.Float64,
  'gender' : Gender,
});
export const Reward = IDL.Record({
  'id' : IDL.Nat,
  'earnedAtNs' : IDL.Int,
  'badge' : IDL.Text,
  'points' : IDL.Nat,
});
export const WorkoutSet = IDL.Record({
  'reps' : IDL.Nat,
  'weightKg' : IDL.Float64,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Vec(WorkoutSet),
});
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'completedAtNs' : IDL.Int,
  'title' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const WorkoutReminder = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'days' : IDL.Vec(IDL.Nat),
  'timeMinutes' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : FoodProduct, 'err' : IDL.Text });
export const SearchResult = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : Profile,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addWorkoutReminder' : IDL.Func(
      [IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
  'deleteFoodEntry' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeProofs' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChallengeProof)],
      ['query'],
    ),
  'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getDailyFoodLog' : IDL.Func([], [DailyFoodLog], ['query']),
  'getDietTarget' : IDL.Func([], [DietTarget], ['query']),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getRankInfo' : IDL.Func([], [RankInfo], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listWorkoutReminders' : IDL.Func([], [IDL.Vec(WorkoutReminder)], ['query']),
  'logFood' : IDL.Func([FoodProduct, IDL.Float64], [], []),
  'logWorkout' : IDL.Func([IDL.Text, IDL.Vec(Exercise)], [], []),
  'removeWorkoutReminder' : IDL.Func([IDL.Nat], [Result], []),
  'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [Result], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchFoodByBarcode' : IDL.Func([IDL.Text], [Result_1], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [Result], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
  'submitChallengeProof' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateFoodEntry' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'updateProfile' : IDL.Func([Profile], [], []),
  'updateWorkoutReminder' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CoachType = IDL.Variant({
    'gym' : IDL.Null,
    'basketball' : IDL.Null,
    'swimming' : IDL.Null,
    'football' : IDL.Null,
    'diet' : IDL.Null,
    'cricket' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'goal' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : IDL.Text,
  });
  const ChatRequest = IDL.Record({
    'coach' : CoachType,
    'message' : IDL.Text,
    'profile' : UserProfile,
  });
  const ChatResponse = IDL.Record({ 'reply' : IDL.Text });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ChallengeProof = IDL.Record({
    'id' : IDL.Nat,
    'proofRef' : IDL.Text,
    'challengeId' : IDL.Nat,
    'submittedAtNs' : IDL.Int,
  });
  const ChallengeStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'status' : ChallengeStatus,
    'title' : IDL.Text,
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'target' : IDL.Nat,
    'rewardBadge' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'sentAtNs' : IDL.Int,
    'from' : IDL.Principal,
    'text' : IDL.Text,
  });
  const Conversation = IDL.Record({
    'messages' : IDL.Vec(ChatMessage),
    'friend' : IDL.Principal,
  });
  const FoodProduct = IDL.Record({
    'fat' : IDL.Float64,
    'carbs' : IDL.Float64,
    'code' : IDL.Text,
    'calories' : IDL.Float64,
    'name' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const FoodLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'loggedAtNs' : IDL.Int,
    'servingSize' : IDL.Float64,
    'product' : FoodProduct,
  });
  const DailyFoodLog = IDL.Record({
    'totalCarbs' : IDL.Float64,
    'totalFat' : IDL.Float64,
    'entries' : IDL.Vec(FoodLogEntry),
    'totalCalories' : IDL.Float64,
    'totalProtein' : IDL.Float64,
  });
  const DietTarget = IDL.Record({
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const FriendRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const FriendRequest = IDL.Record({
    'to' : IDL.Principal,
    'status' : FriendRequestStatus,
    'from' : IDL.Principal,
  });
  const RankTier = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'diamond' : IDL.Null,
    'platinum' : IDL.Null,
    'silver' : IDL.Null,
  });
  const RankInfo = IDL.Record({
    'xp' : IDL.Nat,
    'tier' : RankTier,
    'level' : IDL.Nat,
    'xpToNextLevel' : IDL.Nat,
  });
  const FriendView = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'rank' : RankInfo,
    'challengeProgress' : IDL.Vec(Challenge),
  });
  const ActivityLevel = IDL.Variant({
    'active' : IDL.Null,
    'veryActive' : IDL.Null,
    'light' : IDL.Null,
    'sedentary' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const FitnessGoal = IDL.Variant({
    'gain' : IDL.Null,
    'lose' : IDL.Null,
    'maintain' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'activityLevel' : ActivityLevel,
    'targetSport' : IDL.Text,
    'heightCm' : IDL.Float64,
    'goal' : FitnessGoal,
    'name' : IDL.Text,
    'weightKg' : IDL.Float64,
    'gender' : Gender,
  });
  const Reward = IDL.Record({
    'id' : IDL.Nat,
    'earnedAtNs' : IDL.Int,
    'badge' : IDL.Text,
    'points' : IDL.Nat,
  });
  const WorkoutSet = IDL.Record({ 'reps' : IDL.Nat, 'weightKg' : IDL.Float64 });
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'sets' : IDL.Vec(WorkoutSet),
  });
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'completedAtNs' : IDL.Int,
    'title' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const WorkoutReminder = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'days' : IDL.Vec(IDL.Nat),
    'timeMinutes' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : FoodProduct, 'err' : IDL.Text });
  const SearchResult = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : Profile,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_2], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addWorkoutReminder' : IDL.Func(
        [IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chat' : IDL.Func([ChatRequest], [ChatResponse], []),
    'deleteFoodEntry' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeProofs' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChallengeProof)],
        ['query'],
      ),
    'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getDailyFoodLog' : IDL.Func([], [DailyFoodLog], ['query']),
    'getDietTarget' : IDL.Func([], [DietTarget], ['query']),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendRequest)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getRankInfo' : IDL.Func([], [RankInfo], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listWorkoutReminders' : IDL.Func(
        [],
        [IDL.Vec(WorkoutReminder)],
        ['query'],
      ),
    'logFood' : IDL.Func([FoodProduct, IDL.Float64], [], []),
    'logWorkout' : IDL.Func([IDL.Text, IDL.Vec(Exercise)], [], []),
    'removeWorkoutReminder' : IDL.Func([IDL.Nat], [Result], []),
    'respondToFriendRequest' : IDL.Func(
        [IDL.Principal, IDL.Bool],
        [Result],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchFoodByBarcode' : IDL.Func([IDL.Text], [Result_1], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], ['query']),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [Result], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [Result], []),
    'submitChallengeProof' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateFoodEntry' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'updateProfile' : IDL.Func([Profile], [], []),
    'updateWorkoutReminder' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat), IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };