/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface Challenge {
    id: bigint;
    status: ChallengeStatus;
    title: string;
    rewardPoints: bigint;
    description: string;
    progress: bigint;
    target: bigint;
    rewardBadge: string;
}
export interface ChallengeProof {
    id: bigint;
    proofRef: string;
    challengeId: bigint;
    submittedAtNs: bigint;
}
export interface ChatMessage {
    id: bigint;
    to: Principal;
    sentAtNs: bigint;
    from: Principal;
    text: string;
}
export interface ChatRequest {
    coach: CoachType;
    message: string;
    profile: UserProfile;
}
export interface ChatResponse {
    reply: string;
}
export interface Conversation {
    messages: Array<ChatMessage>;
    friend: Principal;
}
export interface DailyFoodLog {
    totalCarbs: number;
    totalFat: number;
    entries: Array<FoodLogEntry>;
    totalCalories: number;
    totalProtein: number;
}
export interface DietTarget {
    fat: bigint;
    carbs: bigint;
    calories: bigint;
    protein: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Exercise {
    name: string;
    sets: Array<WorkoutSet>;
}
export interface FoodLogEntry {
    id: bigint;
    loggedAtNs: bigint;
    servingSize: number;
    product: FoodProduct;
}
export interface FoodProduct {
    fat: number;
    carbs: number;
    code: string;
    calories: number;
    name: string;
    protein: number;
}
export interface FriendRequest {
    to: Principal;
    status: FriendRequestStatus;
    from: Principal;
}
export interface FriendView {
    principal: Principal;
    name: string;
    rank: RankInfo;
    challengeProgress: Array<Challenge>;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface Profile {
    age: bigint;
    activityLevel: ActivityLevel;
    targetSport: string;
    heightCm: number;
    goal: FitnessGoal;
    name: string;
    weightKg: number;
    gender: Gender;
}
export interface RankInfo {
    xp: bigint;
    tier: RankTier;
    level: bigint;
    xpToNextLevel: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: FoodProduct;
} | {
    __kind__: "err";
    err: string;
};
export type Result_2 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Result__1 {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Reward {
    id: bigint;
    earnedAtNs: bigint;
    badge: string;
    points: bigint;
}
export interface SearchResult {
    principal: Principal;
    profile: Profile;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface UserProfile {
    age: bigint;
    goal: string;
    weightKg: number;
    gender: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Workout {
    id: bigint;
    completedAtNs: bigint;
    title: string;
    exercises: Array<Exercise>;
}
export interface WorkoutReminder {
    id: bigint;
    title: string;
    days: Array<bigint>;
    timeMinutes: bigint;
}
export interface WorkoutSet {
    reps: bigint;
    weightKg: number;
}
export enum ActivityLevel {
    active = "active",
    veryActive = "veryActive",
    light = "light",
    sedentary = "sedentary",
    moderate = "moderate"
}
export enum ChallengeStatus {
    active = "active",
    completed = "completed"
}
export enum CoachType {
    gym = "gym",
    basketball = "basketball",
    swimming = "swimming",
    football = "football",
    diet = "diet",
    cricket = "cricket"
}
export enum FitnessGoal {
    gain = "gain",
    lose = "lose",
    maintain = "maintain"
}
export enum FriendRequestStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum RankTier {
    bronze = "bronze",
    gold = "gold",
    diamond = "diamond",
    platinum = "platinum",
    silver = "silver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result_2>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addWorkoutReminder(days: Array<bigint>, timeMinutes: bigint, title: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    chat(req: ChatRequest): Promise<ChatResponse>;
    deleteFoodEntry(entryId: bigint): Promise<void>;
    execute(qJson: string): Promise<Result__1>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getChallengeProofs(challengeId: bigint): Promise<Array<ChallengeProof>>;
    getChallenges(): Promise<Array<Challenge>>;
    getConversation(friend: Principal): Promise<Array<ChatMessage>>;
    getConversations(): Promise<Array<Conversation>>;
    getDailyFoodLog(): Promise<DailyFoodLog>;
    getDietTarget(): Promise<DietTarget>;
    getFriendRequests(): Promise<Array<FriendRequest>>;
    getFriends(): Promise<Array<FriendView>>;
    getProfile(): Promise<Profile | null>;
    getRankInfo(): Promise<RankInfo>;
    getRewards(): Promise<Array<Reward>>;
    getWorkouts(): Promise<Array<Workout>>;
    isCallerAdmin(): Promise<boolean>;
    listWorkoutReminders(): Promise<Array<WorkoutReminder>>;
    logFood(product: FoodProduct, servingSize: number): Promise<void>;
    logWorkout(title: string, exercises: Array<Exercise>): Promise<void>;
    removeWorkoutReminder(id: bigint): Promise<Result>;
    respondToFriendRequest(from: Principal, accept: boolean): Promise<Result>;
    schema(): Promise<string>;
    searchFoodByBarcode(barcode: string): Promise<Result_1>;
    searchUsers(name: string): Promise<Array<SearchResult>>;
    sendFriendRequest(to: Principal): Promise<Result>;
    sendMessage(to: Principal, text: string): Promise<Result>;
    submitChallengeProof(challengeId: bigint, proofRef: string): Promise<Result>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateFoodEntry(entryId: bigint, servingSize: number): Promise<void>;
    updateProfile(profile: Profile): Promise<void>;
    updateWorkoutReminder(id: bigint, days: Array<bigint>, timeMinutes: bigint, title: string): Promise<Result>;
}
import type { ActivityLevel as _ActivityLevel, Cell as _Cell, Challenge as _Challenge, ChallengeStatus as _ChallengeStatus, ChatRequest as _ChatRequest, CoachType as _CoachType, Error as _Error, FitnessGoal as _FitnessGoal, FoodProduct as _FoodProduct, FriendRequest as _FriendRequest, FriendRequestStatus as _FriendRequestStatus, FriendView as _FriendView, Gender as _Gender, Profile as _Profile, RankInfo as _RankInfo, RankTier as _RankTier, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result__1 as _Result__1, SearchResult as _SearchResult, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_2_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addWorkoutReminder(arg0: Array<bigint>, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutReminder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutReminder(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async chat(arg0: ChatRequest): Promise<ChatResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.chat(to_candid_ChatRequest_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.chat(to_candid_ChatRequest_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteFoodEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodEntry(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result__1_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChallengeProofs(arg0: bigint): Promise<Array<ChallengeProof>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallengeProofs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallengeProofs(arg0);
            return result;
        }
    }
    async getChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChallenges();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChallenges();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getConversations(): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return result;
        }
    }
    async getDailyFoodLog(): Promise<DailyFoodLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyFoodLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyFoodLog();
            return result;
        }
    }
    async getDietTarget(): Promise<DietTarget> {
        if (this.processError) {
            try {
                const result = await this.actor.getDietTarget();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDietTarget();
            return result;
        }
    }
    async getFriendRequests(): Promise<Array<FriendRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<FriendView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRankInfo(): Promise<RankInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getRankInfo();
                return from_candid_RankInfo_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRankInfo();
            return from_candid_RankInfo_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewards(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getWorkouts(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkouts();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listWorkoutReminders(): Promise<Array<WorkoutReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWorkoutReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWorkoutReminders();
            return result;
        }
    }
    async logFood(arg0: FoodProduct, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logFood(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFood(arg0, arg1);
            return result;
        }
    }
    async logWorkout(arg0: string, arg1: Array<Exercise>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0, arg1);
            return result;
        }
    }
    async removeWorkoutReminder(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkoutReminder(arg0);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkoutReminder(arg0);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToFriendRequest(arg0: Principal, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToFriendRequest(arg0, arg1);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToFriendRequest(arg0, arg1);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchFoodByBarcode(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFoodByBarcode(arg0);
                return from_candid_Result_1_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFoodByBarcode(arg0);
            return from_candid_Result_1_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsers(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendFriendRequest(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitChallengeProof(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.submitChallengeProof(arg0, arg1);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitChallengeProof(arg0, arg1);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateFoodEntry(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodEntry(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_Profile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_Profile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWorkoutReminder(arg0: bigint, arg1: Array<bigint>, arg2: bigint, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkoutReminder(arg0, arg1, arg2, arg3);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkoutReminder(arg0, arg1, arg2, arg3);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityLevel_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLevel): ActivityLevel {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ChallengeStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChallengeStatus): ChallengeStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Challenge_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Challenge): Challenge {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FitnessGoal_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessGoal): FitnessGoal {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequestStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequestStatus): FriendRequestStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRequest): FriendRequest {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_FriendView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendView): FriendView {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_RankInfo_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankInfo): RankInfo {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_RankTier_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RankTier): RankTier {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResult_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResult): SearchResult {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n13(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n17(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ChallengeStatus;
    title: string;
    rewardPoints: bigint;
    description: string;
    progress: bigint;
    target: bigint;
    rewardBadge: string;
}): {
    id: bigint;
    status: ChallengeStatus;
    title: string;
    rewardPoints: bigint;
    description: string;
    progress: bigint;
    target: bigint;
    rewardBadge: string;
} {
    return {
        id: value.id,
        status: from_candid_ChallengeStatus_n24(_uploadFile, _downloadFile, value.status),
        title: value.title,
        rewardPoints: value.rewardPoints,
        description: value.description,
        progress: value.progress,
        target: value.target,
        rewardBadge: value.rewardBadge
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Principal;
    status: _FriendRequestStatus;
    from: Principal;
}): {
    to: Principal;
    status: FriendRequestStatus;
    from: Principal;
} {
    return {
        to: value.to,
        status: from_candid_FriendRequestStatus_n29(_uploadFile, _downloadFile, value.status),
        from: value.from
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    rank: _RankInfo;
    challengeProgress: Array<_Challenge>;
}): {
    principal: Principal;
    name: string;
    rank: RankInfo;
    challengeProgress: Array<Challenge>;
} {
    return {
        principal: value.principal,
        name: value.name,
        rank: from_candid_RankInfo_n34(_uploadFile, _downloadFile, value.rank),
        challengeProgress: from_candid_vec_n21(_uploadFile, _downloadFile, value.challengeProgress)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    tier: _RankTier;
    level: bigint;
    xpToNextLevel: bigint;
}): {
    xp: bigint;
    tier: RankTier;
    level: bigint;
    xpToNextLevel: bigint;
} {
    return {
        xp: value.xp,
        tier: from_candid_RankTier_n36(_uploadFile, _downloadFile, value.tier),
        level: value.level,
        xpToNextLevel: value.xpToNextLevel
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    activityLevel: _ActivityLevel;
    targetSport: string;
    heightCm: number;
    goal: _FitnessGoal;
    name: string;
    weightKg: number;
    gender: _Gender;
}): {
    age: bigint;
    activityLevel: ActivityLevel;
    targetSport: string;
    heightCm: number;
    goal: FitnessGoal;
    name: string;
    weightKg: number;
    gender: Gender;
} {
    return {
        age: value.age,
        activityLevel: from_candid_ActivityLevel_n41(_uploadFile, _downloadFile, value.activityLevel),
        targetSport: value.targetSport,
        heightCm: value.heightCm,
        goal: from_candid_FitnessGoal_n43(_uploadFile, _downloadFile, value.goal),
        name: value.name,
        weightKg: value.weightKg,
        gender: from_candid_Gender_n45(_uploadFile, _downloadFile, value.gender)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: _Profile;
}): {
    principal: Principal;
    profile: Profile;
} {
    return {
        principal: value.principal,
        profile: from_candid_Profile_n39(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): ChallengeStatus {
    return "active" in value ? ChallengeStatus.active : "completed" in value ? ChallengeStatus.completed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): FriendRequestStatus {
    return "pending" in value ? FriendRequestStatus.pending : "accepted" in value ? FriendRequestStatus.accepted : "declined" in value ? FriendRequestStatus.declined : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    diamond: null;
} | {
    platinum: null;
} | {
    silver: null;
}): RankTier {
    return "bronze" in value ? RankTier.bronze : "gold" in value ? RankTier.gold : "diamond" in value ? RankTier.diamond : "platinum" in value ? RankTier.platinum : "silver" in value ? RankTier.silver : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
}): ActivityLevel {
    return "active" in value ? ActivityLevel.active : "veryActive" in value ? ActivityLevel.veryActive : "light" in value ? ActivityLevel.light : "sedentary" in value ? ActivityLevel.sedentary : "moderate" in value ? ActivityLevel.moderate : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
}): FitnessGoal {
    return "gain" in value ? FitnessGoal.gain : "lose" in value ? FitnessGoal.lose : "maintain" in value ? FitnessGoal.maintain : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FoodProduct;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FoodProduct;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Challenge>): Array<Challenge> {
    return value.map((x)=>from_candid_Challenge_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRequest>): Array<FriendRequest> {
    return value.map((x)=>from_candid_FriendRequest_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendView>): Array<FriendView> {
    return value.map((x)=>from_candid_FriendView_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SearchResult>): Array<SearchResult> {
    return value.map((x)=>from_candid_SearchResult_n52(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityLevel_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): _ActivityLevel {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRequest): _ChatRequest {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CoachType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoachType): _CoachType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FitnessGoal_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): _FitnessGoal {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    activityLevel: ActivityLevel;
    targetSport: string;
    heightCm: number;
    goal: FitnessGoal;
    name: string;
    weightKg: number;
    gender: Gender;
}): {
    age: bigint;
    activityLevel: _ActivityLevel;
    targetSport: string;
    heightCm: number;
    goal: _FitnessGoal;
    name: string;
    weightKg: number;
    gender: _Gender;
} {
    return {
        age: value.age,
        activityLevel: to_candid_ActivityLevel_n56(_uploadFile, _downloadFile, value.activityLevel),
        targetSport: value.targetSport,
        heightCm: value.heightCm,
        goal: to_candid_FitnessGoal_n58(_uploadFile, _downloadFile, value.goal),
        name: value.name,
        weightKg: value.weightKg,
        gender: to_candid_Gender_n60(_uploadFile, _downloadFile, value.gender)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coach: CoachType;
    message: string;
    profile: UserProfile;
}): {
    coach: _CoachType;
    message: string;
    profile: _UserProfile;
} {
    return {
        coach: to_candid_CoachType_n9(_uploadFile, _downloadFile, value.coach),
        message: value.message,
        profile: value.profile
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoachType): {
    gym: null;
} | {
    basketball: null;
} | {
    swimming: null;
} | {
    football: null;
} | {
    diet: null;
} | {
    cricket: null;
} {
    return value == CoachType.gym ? {
        gym: null
    } : value == CoachType.basketball ? {
        basketball: null
    } : value == CoachType.swimming ? {
        swimming: null
    } : value == CoachType.football ? {
        football: null
    } : value == CoachType.diet ? {
        diet: null
    } : value == CoachType.cricket ? {
        cricket: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityLevel): {
    active: null;
} | {
    veryActive: null;
} | {
    light: null;
} | {
    sedentary: null;
} | {
    moderate: null;
} {
    return value == ActivityLevel.active ? {
        active: null
    } : value == ActivityLevel.veryActive ? {
        veryActive: null
    } : value == ActivityLevel.light ? {
        light: null
    } : value == ActivityLevel.sedentary ? {
        sedentary: null
    } : value == ActivityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessGoal): {
    gain: null;
} | {
    lose: null;
} | {
    maintain: null;
} {
    return value == FitnessGoal.gain ? {
        gain: null
    } : value == FitnessGoal.lose ? {
        lose: null
    } : value == FitnessGoal.maintain ? {
        maintain: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
